# Generated by Django 3.2.5 on 2021-07-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created',
        ),
    ]
